# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 500)
        MainWindow.setMinimumSize(QtCore.QSize(300, 500))
        MainWindow.setMaximumSize(QtCore.QSize(300, 500))
        MainWindow.setStyleSheet("QWidget {\n"
"    color: white;    \n"
"    background-color: rgb(11, 11, 11);\n"
"    border-top-color: rgb(85, 255, 12);\n"
"}\n"
"\n"
"QPushButton {    \n"
"    background-color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(126, 126, 126);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    \n"
"    background-color: rgb(255, 30, 41);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.l_timer = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.l_timer.setFont(font)
        self.l_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.l_timer.setObjectName("l_timer")
        self.verticalLayout.addWidget(self.l_timer)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Round = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Round.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Round.sizePolicy().hasHeightForWidth())
        self.btn_Round.setSizePolicy(sizePolicy)
        self.btn_Round.setAccessibleName("")
        self.btn_Round.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_Round.setStyleSheet("")
        self.btn_Round.setObjectName("btn_Round")
        self.horizontalLayout.addWidget(self.btn_Round)
        self.btn_Start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.btn_Start.sizePolicy().hasHeightForWidth())
        self.btn_Start.setSizePolicy(sizePolicy)
        self.btn_Start.setStyleSheet("")
        self.btn_Start.setObjectName("btn_Start")
        self.horizontalLayout.addWidget(self.btn_Start)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Секундомер"))
        self.l_timer.setText(_translate("MainWindow", "00:00:000"))
        self.btn_Round.setText(_translate("MainWindow", "Круг"))
        self.btn_Start.setText(_translate("MainWindow", "Старт"))
